In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [5]:
dfM=pd.read_csv('Datos_limpios_Mexico.csv')
dfM= dfM.drop(['Unnamed: 0'], axis=1)
dfM.head(5)

last_scraped           source  \
0   25/09/2024      city scrape   
1   26/09/2024  previous scrape   
2   26/09/2024      city scrape   
3   25/09/2024      city scrape   
4   25/09/2024      city scrape   

                                               name  \
0                                       Villa Dante   
1                                      Condesa Haus   
2                 2 bedroom apt. deco bldg, Condesa   
3  Beautiful light Studio Coyoacan- full equipped !   
4                                NEW  DESIGNER LOFT   

                                         description host_name  host_since  \
0  Dentro de Villa un estudio de arte con futon, ...      Dici  28/06/2010   
1  A new concept of hosting in mexico through a b...  Fernando  09/08/2010   
2  Comfortably furnished, sunny, 2 bedroom apt., ...  Nicholas  04/01/2011   
3  COYOACAN designer studio quiet & safe! well eq...    Trisha  24/08/2010   
4  Is the best ever place triple L <br />Location...    Andrea  27/04/2011   

         host_location                                         host_about  \
0  Mexico City, Mexico  Master in visual arts, film photography & Mark...   
1  Mexico City, Mexico  Condesa Haus  offers independent  studios and ...   
2  Mexico City, Mexico  I am a journalist writing about food, (book an...   
3  Mexico City, Mexico  I am a mother, documentary film maker and phot...   
4  Mexico City, Mexico  I Leave in Mexico City... I am an Architect an...   

   host_response_time host_response_rate  ... number_of_reviews_l30d  \
0  a few days or more                 0%  ...                    0.0   
1      within an hour               100%  ...                    0.0   
2      within an hour                71%  ...                    0.0   
3  within a few hours               100%  ...                    2.0   
4      within an hour               100%  ...                    0.0   

  review_scores_rating review_scores_accuracy review_scores_cleanliness  \
0                 4.80                   4.90                      4.80   
1                 4.58                   4.56                      4.70   
2                 4.90                   4.81                      4.75   
3                 4.91                   4.90                      4.96   
4                 4.91                   5.00                      5.00   

  review_scores_checkin review_scores_communication review_scores_location  \
0                  4.90                        4.90                   4.90   
1                  4.87                        4.78                   4.98   
2                  4.94                        4.92                   4.98   
3                  4.96                        4.98                   4.96   
4                  5.00                        4.73                   4.91   

  review_scores_value calculated_host_listings_count reviews_per_month  
0                4.70                            1.0              1.20  
1                4.48                            8.0              0.41  
2                4.91                            2.0              0.31  
3                4.92                            3.0              0.83  
4                4.82                            3.0              0.11  

[5 rows x 49 columns]

In [57]:
unico=np.unique(dfM['availability_30'])
unico

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [58]:
unico=np.unique(dfM['instant_bookable'])
unico

array(['f', 't'], dtype=object)

In [59]:
unico=np.unique(dfM['host_listings_count'])
unico

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  6.2,  7. ,  8. ,  9. , 10. ,
       11. , 12. , 13. , 14. , 15. , 16. , 17. , 18. , 19. , 20. , 21. ,
       22. , 23. , 24. , 25. , 26. , 27. , 28. , 29. , 30. , 31. , 32. ,
       33. ])

In [65]:
dfM['instant_bookable'] = dfM['instant_bookable'].map({'t': 1, 'f': 0})

In [66]:
Vars_Indep=dfM[['availability_30','instant_bookable','host_listings_count']]
Var_Dep=dfM['has_availability'] #variable objetivo

In [67]:
X=Vars_Indep
y=Var_Dep

In [69]:
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.3, random_state=None)

In [70]:
#se escalan todos los datos
escalar= StandardScaler()

In [71]:
#para realizar el escalamiento de las variables X tanto de entrenamiento como de prueba 
X_train= escalar.fit_transform(X_train)
X_test= escalar.transform(X_test)

In [72]:
#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo= LogisticRegression()

In [73]:
algoritmo.fit(X_train,y_train)

LogisticRegression()

In [74]:
y_pred=algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], shape=(7975,), dtype=object)

In [75]:
modelo = LogisticRegression(class_weight='balanced')
modelo.fit(X_train, y_train)
y_pred = modelo.predict(X_test)

In [76]:
#matriz de confusion
from sklearn.metrics import confusion_matrix
matriz= confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

Matriz de Confusion:
[[ 233   62]
 [2278 5402]]


In [77]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred , average='binary',pos_label='t')
print('Precision del modelo')
print(precision)

Precision del modelo
0.9886530014641288


In [78]:
#calcular exactitu del modelo
from sklearn.metrics import accuracy_score

exactitud=accuracy_score(y_test,y_pred)
print('Exactitud del modelo')
print(exactitud)

Exactitud del modelo
0.7065830721003135


In [79]:
#calcular sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad=recall_score(y_test,y_pred,average='binary',pos_label='f')
print('Sensibilidad del modelo')
print(sensibilidad)

Sensibilidad del modelo
0.7898305084745763
